# Generated by Django 2.0.4 on 2018-04-24 00:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=20)),
                ('thumbnail', models.ImageField(default='default.png', upload_to='')),
                ('previewText', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('background', models.ImageField(default='default.png', upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
