# Generated by Django 2.0.4 on 2018-04-25 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180425_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
