# Generated by Django 2.0.4 on 2018-04-25 21:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180426_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(max_length=25),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='textPreview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
